#ifndef OPERATIONS_H
#define OPERATIONS_H

typedef enum {
    OPERATION_GET_FILES_LIST,
    OPERATION_GET_FILE,
    OPERATION_SEND_FILE,
    OPERATION_REMOVE_FILE,
    OPERATION_UPDATE_FILE
} Operation;


#endif // !OPERATIONS_H
